# Generated by Django 4.2.5 on 2023-10-02 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_product_units_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parties',
            name='name',
            field=models.CharField(max_length=25),
        ),
    ]
