# Generated by Django 4.2.5 on 2023-10-05 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_parties_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
