# Generated by Django 4.2.5 on 2023-10-05 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_delete_customuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpenseCategory',
            fields=[
                ('name', models.CharField(max_length=255, primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'ExpenseCategory',
            },
        ),
        migrations.RenameModel(
            old_name='Category',
            new_name='ProductCategory',
        ),
        migrations.AlterModelTable(
            name='productcategory',
            table='ProductCategory',
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('expense', models.CharField(max_length=25)),
                ('date', models.DateTimeField()),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(max_length=255)),
                ('note', models.CharField(max_length=25)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.expensecategory')),
            ],
            options={
                'db_table': 'Expense',
            },
        ),
    ]
